apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
        - name: project-backend
          image: laurihakala/project-backend:47e7630d0c43