apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project-fronted-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-frontend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50