apiVersion: v1
kind: Service
metadata:
  namespace: main
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432