apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/service.yaml
images:
  - name: PROJECT/IMAGE
    newName: laurihakala/projectfront