apiVersion: v1
kind: ConfigMap
metadata:
  namespace: main
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: maindb
  POSTGRES_USER: mainuser
  POSTGRES_PASSWORD: mainpassword