apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: project-backend-svc
spec:
  type: NodePort
  selector:
    app: project-backend
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3001
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432